### ISSUE TITLE
Mensaje de habilitar localizacion

### ISSUE THREAD

**Issue by pcerbino** [leocreo/localia#1]
Cuando se inicia la app en un télefono que no tiene la localización habilitada la app queda "colgada" en la pantalla turquesa de inicio. Debería sugerir al usuario que debe habilitar la localización:

cordova.require('cordova/plugin/diagnostic').switchToLocationSettings();

**Comment by pcerbino** [comment]
http://stackoverflow.com/questions/27441993/redirect-to-location-settings-using-cordova-in-android

**Comment by leocreo** [comment]
No sería mejor que, si no se pudo lograr obtener la geolocalizacion la app ande igual pero no se muestren las distancias? Lo que no sé es donde mostrarle un mensaje para que sepa que puede habilitarla y asi tener las distancias a los lugares. Quizás en cerca del mapa? 
Porque si ya le mostramos al usuario un mensaje que habilite su ubicación ni bien la instala, creo que espanta un poco.

**Comment by pcerbino** [comment]
Las distancias están en los resultados de búsqueda y en la pantalla de anuncio... digo, si en vez de mostrar la distancia (cuando no esta disponible), mostramos un link de "Ver distancia" que lleve a una pantalla que diga que para ver las distancias debe habilitar la localiacion??

**Comment by leocreo** [comment]
Ya se muestra mensaje y se envía a la configuracion. Tambien se realizaron excepciones para evitar errores y cambios en la interfaz. Falta que se refresque el estado si el usuario habilita el GPS pero no recarga la app

**Comment by leocreo** [comment]
Se mejoró toda la geolocalizacion y las detecciones de cambio de ubicacion que vuelven a pedir info de distancias al API.
