### ISSUE TITLE
Corregir orden de distancia y direccion en Places

### ISSUE THREAD

**Issue by leocreo** [leocreo/localia#10]

**Comment by pcerbino** [comment]
Lo esta trayendo ordenado  por distancia, cuando se pasan las variables de lat y lon. 
http://www.localia.com.ar/api/places?city_id=3832734&lat=-31.9833&lon=-64.5667

**Comment by leocreo** [comment]
No, se refería a que los datos de direccion y distancia que aparecen arriba del mapa en el detalle del Place, está roto.
