### ISSUE TITLE
Social Sharing

### ISSUE THREAD

**Issue by pcerbino** [leocreo/localia#7]
Cuando un anuncio se comparte por facebook se abre perfecto, pero debería aparecer algo pre-escrito...

**Comment by leocreo** [comment]
Corregido. De todas formas el compilador da un mensaje raro y aunque el plugin funciona en Android, lo voy a mirar y ya postee un mensaje al creador del plugin para ver si esto es algo para preocuparse.
El Mensaje es que el JAVA del plugin usa un API "Deprecated".
